name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ouzi-dev/commit-status-updater@v1.0.0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build src
    - name: Test
      run: dotnet test src
    - if: always()
      uses: ouzi-dev/commit-status-updater@v1.0.0
      with:
        status: "${{ job.status }}"
